### ISSUE TITLE
No colour syntax highlighting.

### ISSUE THREAD

**Issue by beetlegigg** [mu-editor/mu#1047]
Hello, I've just downloaded and installed the Alpha mu on mac os catalina 10.15.4.   It finds my adafruit 8266 board and I can create and run programs.  But the mu editor does not give any syntax colour highlighting.  Also, if I switch to dark mode the text continues to be in black and thus invisible.   I cant see any settings to change this.  Does anyone have any idea what could be wrong?  Thanks.

**Comment by carlosperate** [comment]
Hi @beetlegigg,


I think these issues are already fixed in the master branch for the next release: https://github.com/mu-editor/mu/issues/936, https://github.com/mu-editor/mu/issues/1027

I'm closing this as "fixed in master", but please do reopen if you still find these issues running from Mu from the master branch as well.
