### ISSUE TITLE
In Windows XP 32 bits (Python 3.4.3)

### ISSUE THREAD

**Issue by tellts** [mu-editor/mu#1091]
Hello. Please tell me if there is a compatible version for installation?

**Comment by tjguk** [comment]
I'm afraid there really isn't. Python itself stopped supporting Windows XP when Microsoft did; and since we expect most people to be using our bundled Windows package, which includes Python, we've not had any particular reason to support older versions. I think we still support 3.5 but that might well become 3.6 in the next release.
