### ISSUE TITLE
Line too long (xx > 79 characters) after click button tidy.

### ISSUE THREAD

**Issue by fraramon** [mu-editor/mu#1146]
Hi, just when I click on tidy, I get a lot of line overrun errors that I can't eliminate.
Thanks for everything...

**Comment by devdanzin** [comment]
Hello, thank you for the report! 
I have suffered from this, but it turned out that clicking the "Check" button again made the errors disappear. Took me a while to figure it out, then later I saw another user with the same issue.

Can you test whether clicking the "Check" button makes the error messages disappear (and reappear if  clicked again)? Does clicking on Tidy make the errors disappear?

If you case is the same as mine, I can open an issue about making easier to understand the button behavior (like change colour when Check is active).

**Comment by dybber** [comment]
@fraramon Could you post some example code? 

I can't replicate this behaviour. For me it seems tidy does indeed work, unless I do something like the following, where tidy is unable to find a place to wrap the line:

```
a_very_long_variable_name_which_tidy_is_unable_to_shorten_to_something_below_79_chars = 1
```

**Comment by devdanzin** [comment]
It's possible to get check to complain and tidy not to help with this code, which would seem to have two kinds of wrappable sites:

```python
import random
colors = ["red", "orange", "yellow"] + ["gray", "black", "blue", "purple", "green"]
color = random.choice(colors)
```

Oh, it's from the settings we use for black in tidy_code, this fixes it:

```diff
diff --git a/mu/logic.py b/mu/logic.py
index bdc4cfb..a43647a 100644
--- a/mu/logic.py
+++ b/mu/logic.py
@@ -1839,7 +1839,7 @@ class Editor(QObject):
             source_code = tab.text()
             logger.info("Tidy code.")
             logger.info(source_code)
-            filemode = FileMode(target_versions=PY36_VERSIONS, line_length=88)
+            filemode = FileMode(target_versions=PY36_VERSIONS, line_length=79)
             tidy_code = format_str(source_code, mode=filemode)
             # The following bypasses tab.setText which resets the undo history.
             # Doing it this way means the user can use CTRL-Z to undo the
```

While 88 was a deliberate choice in #687, maybe check should accept longer lines to avoid a gap between check and tidy.

**Comment by dybber** [comment]
Ah, good find! 

I think I agree, instead of your patch we should increase max line length for Pycodestyle to allow up to 88 chars, and let the number be configured as a single variable used for both tidy and check, so we don't get this problem again if we redecide and want to set it to 79 at some point and forget to change it at both locations.

/Martin
