### ISSUE TITLE
crash report installing 1.1 beta 4 

### ISSUE THREAD

**Issue by dsssssssss9** [mu-editor/mu#1488]
OS: Ubuntu 20.04.2 LTS x86_64 

currently running 1.1 beta 3 with no problems.

attempted to install 1.1 beta 4 - which crashed after the animated snake screen with the attached log file. I had to upload this manually as the web page that pops up after beta 4 crashes does find the location of the log file

uninstalled beta 4 & reinstalled beta 3 for the time being
[mu.log](https://github.com/mu-editor/mu/files/6332185/mu.log)

**Comment by carlosperate** [comment]
Thanks for the report and the log @dsssssssss9!

I believe the issue here might be https://github.com/mu-editor/mu/issues/1421. I think there might be two ways to work around this issue.

Option1:
- First `pip uninstall mu-editor`
- Check that the `/home/jkd/.local/lib/python3.8/site-packages/mu/` directory has been fully removed
   - if it's still present you can manually remove it
- Then `pip install mu-editor` again and this time it should work

Option 2:
- If you are currently running beta.3, then install beta.4 again
- Go to the `/home/jkd/.local/lib/python3.8/site-packages/mu/wheels` directory and remove all files **except** `__init__.py` and `__main__.py`. 
- Then run Mu and this time it should work
    - The first run will take a bit longer as it will redownload all the files you just deleted, but hopefully it'll fix the issue

**Comment by dsssssssss9** [comment]
HI Carlos

thanks to you i am now looking at a working version of 1.1 beta 4 .

I am very grateful for the effort you took to help me out - particularly as you ( and the rest of the fantastic MU team! ) must be so so busy at the moment?

do you think this will be the best way to install future updates?

Regards

**Comment by carlosperate** [comment]
I'm glad you were able to resolve the issue!
It's a busy time and we are all volunteers, but it's great to be able to able to work with a great community. Is thanks to people like you testing the editor, finding these issues, and investing the time to let us know, that we can do all this, so thank you for your time as well!

We'll be able to fix this issue for the next release, so this workaround should be only needed for beta.4, and future pip upgrades should work again 👍 

I'll close this issue as resolved, thanks for testing and don't hesitate to open more issues if you find other problems :)
