### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ocho8a** [mu-editor/mu#1616]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: es_SV
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 283, in installed
    next(iterlines)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 626, in create
    self.register_baseline_packages()
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 751, in register_baseline_packages
    packages = list(self.pip.installed())
  File "C:\Users\Newsaver\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 289, in installed
    raise VirtualEnvironmentError("Unable to parse installed packages")
mu.virtual_environment.VirtualEnvironmentError: Unable to parse installed packages

```

**Comment by carlosperate** [comment]
Thanks for the report @Ocho8a!
Would you be able to attach the Mu log to this GH Issue as well? It'll be really useful to us for debugging.
I think it's possible you might have dragged the file to the title text field, if that's the case you'd have to drag&drop it into the text field of a new comment here.

File should be located in: `C:\Users\Newsaver\AppData\Local\python\mu\Logs\mu.log`

**Comment by carlosperate** [comment]
Hi @Ocho8a,

Are you able to attach the log? File should be in `C:\Users\Newsaver\AppData\Local\python\mu\Logs\mu.log`.

Would you be able to check if beta.5 has resolved the issue let us know the result?
https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.5

Thanks!

**Comment by carlosperate** [comment]
@BarryButler have you been able to test this with beta.5? There has been some changes in this area that we think could have helped with this issue: https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.5

If you could also attach the log (located in `C:\Users\Newsaver\AppData\Local\python\mu\Logs\mu.log`) that would really help us investigate this issue.

**Comment by BarryButler** [comment]
Beta 5 works fine.  Thankyou.


Regards,

Barry Butler
Teacher (Digital Technology, Aviation, Maths, Science)

[2019 Email Signature Block]
------------------------

This message (including attachments) is intended for the addressee named above. It may also be confidential, privileged and/or subject to copyright. If you wish to forward this message to others, you must first obtain the permission of the author. If you are not the addressee named above, you must not disseminate, copy, communicate or otherwise use or take any action in reliance on this message. You understand that any privilege or confidentiality attached to this message is not waived, lost or destroyed because you have received this message in error. If you have received this message in error please notify the sender and delete from any computer. Unless explicitly attributed, the opinions expressed in this message do not necessarily represent the official position or opinions of the State of Queensland or the Department of Education, Training and Employment. Whilst all care has been taken, the Department of Education, Training and Employment disclaims all liability for loss or damage to person or property arising from this message being infected by computer virus or other contamination.

**Comment by carlosperate** [comment]
Awesome, thanks for the update!
