### ISSUE TITLE
Can't open help menu

### ISSUE THREAD

**Issue by titimoby** [mu-editor/mu#171]
From Mu 0.9.11, I click on Help icon
Nothing happens but the terminal shows the following error:

`/usr/lib/firefox/firefox: /tmp/_MEIvIjOGD/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
`

**Comment by ntoll** [comment]
Hmm.... your default browser appears to be Firefox right..? I suspect that it's not installed correctly since the error you report is a message from your OS that shows up in Mu's logs complaining about Firefox.

Essentially, Mu has asked the OS to start its default browser and point it at our online documentation. The OS is reporting that it can't start Firefox. Not a lot Mu can do about that... so can you check your browser configuration..?

**Comment by titimoby** [comment]
My default browser is Firefox.
I can check ... but don't know what to search for.
All others applications i have that launch browser for help pages seems to work.
If you have any clue, I'll check. I need to understand it because I have a workshop with kids next sunday and I only have access to the machines at  that moment.
Thanks

**Comment by carlosperate** [comment]
See if something like this could fix it: http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
Can you run firefox from the command line?

**Comment by ntoll** [comment]
@titimoby any progress on this?

**Comment by titimoby** [comment]
No progress on this topic, which I understand is not a problem from Mu editor.
I just come back from a workshop were I used Mu with kids and it was great.
I need now to find enough time to contribute to a french documentation to reach younger ones.

**Comment by carlosperate** [comment]
@titimoby sounds like the original issue was with firefox instead of Mu, so I'll close this one. Feel free to open it again otherwise.
