### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by gallaugher** [mu-editor/mu#1717]
**REMEMBER TO ATTACH YOUR LOG FILE**
[mu.log](https://github.com/mu-editor/mu/files/6870830/mu.log)

Version: 1.1.0.beta.5
Locale: en_US
Platform: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/main.py", line 254, in on_modified
    state_lbl.setPixmap(load_pixmap("document-dirty.svg"))
RuntimeError: wrapped C/C++ object of type QLabel has been deleted

```

**Comment by carlosperate** [comment]
Hi @gallaugher, thank you very much for the report!

I believe this might be the same issue as https://github.com/mu-editor/mu/issues/1474, which has been fixed with PR https://github.com/mu-editor/mu/pull/1694.

I'll close this issue as resolved, since the next Mu beta release will include this fix.

Thanks again for the report and testing Mu!
