### ISSUE TITLE
Add 'open file in editor' option to file on host drive FILES view

### ISSUE THREAD

**Issue by whaleygeek** [mu-editor/mu#174]
It would be helpful to be able to click on the file in the right hand pane in the FILES view and open it to edit the host version of that file in the default editor for that file. 

e.g. if you have a text file with some data in it, instead of having to find out where Mu stores those files (userdir/python) and navigating there to edit it, you could just double click on it and open it in a text editor. I'd be happy if this action was limited to just .txt and .py files for example, and if it allowed that file to be opened in a new tabbed pane in the Mu editor.

**Comment by carlosperate** [comment]
Yeah, I completely agree this would be the expected behaviour by most people.

I would probably go as far as to suggest to be able open the microbit files as well, but in the spirit of keeping things simple I'd probably suggest to instead open a message box asking if you'd like to copy the file into the computer first and open from there (so clicking "OK" would do the copy and opening).

**Comment by whaleygeek** [comment]
@carlosperate @ntoll is this on the radar at all do you know?

**Comment by ZanderBrown** [comment]
I'll have a look into this later as it shouldn't be too difficult to achive

**Comment by DavidWhaleMEF** [comment]
Super, thanks @ZanderBrown this is ace!
