### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ayushidg** [mu-editor/mu#1802]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: en_US
Platform: Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 x86_64

```
Traceback (most recent call last):
  File "/private/var/folders/zz/xth13jt514lcnlmgfw_x9rgw0000gn/T/AppTranslocation/94D16CB9-0FED-433F-B984-043B089824B8/d/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/main.py", line 254, in on_modified
    state_lbl.setPixmap(load_pixmap("document-dirty.svg"))
RuntimeError: wrapped C/C++ object of type QLabel has been deleted

```

Bro your stupid app just crashed and now I have to redo all my work because it crashed. And what is all the extra stuff on the top thank u fix this bye.

**Comment by carlosperate** [comment]
Hi @ayushidg, thank you very much for the report!

I believe this might be the same issue as https://github.com/mu-editor/mu/issues/1474, which has been fixed with PR https://github.com/mu-editor/mu/pull/1694.

I'll close this issue as resolved, since the next Mu beta release will include this fix.

Thanks again for the report and testing Mu!
