### ISSUE TITLE
ESP8266 with CP210x from different Vendor

### ISSUE THREAD

**Issue by akatecker** [mu-editor/mu#2358]
### What were you trying to do?

Connect to ESP8266 Board

### What steps did you take to trigger the issue?

When trying to connect to the AZ Delivery "ESP8266 with integrated OLED 0.91 Display" (https://www.az-delivery.de/en/products/esp8266-mikrocontroller-mit-integrierten-0-91-oled-display), Mu Editor shows "no device connected"

### What actually happened?

This board has a **CP2104 compatible** USB chip, Vendor ID is **0x1a86**, Product ID is **0x55d4**. 

Other boards by AZ Delivery & others might also be affected, seams that the manufacturer of the CH340 has released a CP2104 knockoff? 

Anyway, please include this board in the "valid_boards" of modes/esp.py

### Operating System Version

Mac OS 11.13

### Mu Version

1.1.1

### Other Info

Thonny does find the board, but I prefer Mu Editor. Maybe (as a feature request), there should by a user-updatable list of "valid_boards" that is loaded in addition to the hard-coded boards included in the mode files.

**Comment by nxtsem** [comment]
I have an issue with ESP32 boards under Windows.  MU connects properly with Si Labs CP2104 but MU does not recognize the CH9102.    Thonny works properly with both the CP210x and CH910x USB/UART devices.   Microcontroller board developers are switching over to the Ch910x replacement devices due to the significantly lower cost.
