### ISSUE TITLE
Warnings when starting up Mu on Raspberry Pi

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#332]
Warnings are presented when starting up Mu on a Raspberry Pi.

```
pi@raspberrypi:~/mu $ python3 run.py
Logging to /home/pi/.cache/mu/log/mu.log
libEGL warning: DRI2: failed to authenticate

** (python3:17683): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files


Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

It doesnt appear to affect the running of Mu, but I thought it would be a good idea to raise an issue.

**Comment by ntoll** [comment]
This problem is caused where Qt calls a Gtk based dialog provided by the desktop environment (for example the "open file" dialog. The reason is the Gtk dialog is expecting a Gtk parent to belong to, and Mu is a Qt based parent, so no parent is passed since Gtk can't use Qt as a parent.

See https://forum.qt.io/topic/85997/gtk-warning-for-native-qfiledialog-under-linux for more details.

In any case, the message is just annoying without any other apparent side-effect.
