### ISSUE TITLE
Serial vs REPL

### ISSUE THREAD

**Issue by tannewt** [mu-editor/mu#426]
Have you seen people get confused by the REPL button in Mu? I think there is a mismatch between it and user expectation. I think users expect it to simply open the serial connection and display the output from their code. Instead, it connects to serial and also enters the REPL. Is it worth adding a second button or changing this to "Serial" and not having it enter the REPL?

Here is an example: https://forums.adafruit.com/viewtopic.php?f=60&t=133658

Thanks!

**Comment by ntoll** [comment]
Hey hey @tannewt!

This is good feedback and reflects that Mu is used by different sorts of users. I guess the trick is to make the right sort of compromises and/or point people in the right direction when the unexpected happens.

When we first built Mu *lots* of user testing, thought, tearing of hair and gnashing of teeth went into working out what the behaviour of the REPL button should be. We got feedback from teachers and Pythonistas at several workshops we held while making Mu. ;-)

The TL;DR is that users expected the Python prompt rather than serial data (beginners not knowing they could press CTRL-C to drop into the REPL). Furthermore, it was felt that non-beginner developers would probably know about CTRL-D soft reset to restart the device to see serial data from their script.

I don't want to add more buttons, because it's important the UI remains simple. This is especially the case if the main difference is one button automatically sends a CTRL-C to force the Python prompt and another doesn't.

However, the potential for confusion and/or the problems encountered a la the discussion you link to remains. To this end I'm in the middle (as we speak!) of writing the new Mu website, including a tutorial about using the REPL. Part of this will address the points raised above so it'll be clear (for more advanced users) how to see serial data in the REPL. This information will be easily accessible from the "Help" button (although, since the new website isn't released yet, it doesn't work). It's also worth pointing out that if you start the plotter before also starting the REPL, then Mu realises you're probably trying to read data from serial and so doesn't force the Python prompt.

Does this help?

**Comment by carlosperate** [comment]
Maybe there could be a short message in the status bar when the REPL is opened? Something indicating how to reset the board to view the serial data.
To be honest I don't really pay much attention to the bottom of the window, so it's not much of a solution, but it feels like this is the kind of thing that is usually shown there anyway.

**Comment by tannewt** [comment]
This came up again here: https://forums.adafruit.com/viewtopic.php?f=60&t=134891

I think this confusion is an artifact of the file based iteration focus of CircuitPython vs REPL based iteration in MicroPython. Specifically, in CircuitPython, we removed the need to know that CTRL-D is reload because we auto-reload on save.

I totally agree that a button labeled REPL should drop into the prompt. However, I'd rather have a Serial button. File-based workflow is more useful because it allows you to build upon the code you've previously written. The REPL is ephemeral and not reproducible. For file based its confusing to get people to the serial output via the REPL.

**Comment by ntoll** [comment]
@tannewt let's chat at PyCon... :-) I'm sure we can work out the best solution F2F (this may just be a new button called "serial" that works in exactly the same way as REPL, except it doesn't send CTRL-C to stop the running code). Suggestions for a font-awesome icon (https://fontawesome.bootstrapcheatsheets.com/) for this most welcome..! Thoughts..?

**Comment by ntoll** [comment]
Hahahaha... ummm... I'm not sure what I feel about that suggestion either... ;-)

If I'm honest, I prefer the two button approach (clicking one disables the other) quite simply because it's simpler to grok for beginner programmers and makes "vanilla serial" easier to find for those coming from perhaps an Arduino background.

Thoughts..?

**Comment by tannewt** [comment]
tty, list-alt or plug could work for serial. I'll try and play more with mu before PyCon as well. Thanks!

**Comment by jwindberg** [comment]
all this is nice, but I'm working through an adafruit tutorial, and I'm supposed to push the serial button, and there isn't one.
I'm worried less about buttons and more about functionality. Both repl and serial seem like nice things to have.
Not sure I care about buttons vs menus or other options.
So, how do I get the serial output now?
