### ISSUE TITLE
Flash modal popup behaviour change request.

### ISSUE THREAD

**Issue by WayneKeenan** [mu-editor/mu#436]
Please can the way the info in the modal pop-up that appears after pressing flash be presented in a way such that it doesn't have to be manually dismissed, e.g. a status line or a perhaps an auto closing notification bubble in the top corner.

Being able to prevent it from appearing at all via config would be an alternative.

Thanks
Wayne

**Comment by ntoll** [comment]
Hi @WayneKeenan,

Thanks for the feedback! However, I think you're on an old version of Mu, since this was changed several months ago in master and works in exactly the way you suggest. Please *DO NOT* use the version of Mu currently available via the main website (http://codewith.mu/) since this is the old version. I hope to update things VERY SOON so the latest version of the beta is available for download via the website. However, until such time, please use the version you get from using `pip` to install the editor (which is tracking the beta releases). You'll see we've already made the change you suggest! ;-)

**Comment by WayneKeenan** [comment]
ah, that's better. ooo, lots of new toys too!  thanks @ntoll

**Comment by ntoll** [comment]
You're welcome @WayneKeenan -- all feedback most welcome! :-)
