### ISSUE TITLE
Persistent REPL command history

### ISSUE THREAD

**Issue by WayneKeenan** [mu-editor/mu#449]
Add an option/feature to intercept what is typed in the REPL in Mu so that users commands can persists over script flashing. 

Perhaps, if Mu captured SHIFT-UpArrow that would browse (and insert into the live REPL) the Mu recorded REPL history and Up Arrow would still be the normal behaviour.

Maybe the REPL history Mu captures can (optionally) be saved to disk.

**Comment by dybber** [comment]
Hi @WayneKeenan. Thanks for the suggestion.

However, what you are suggesting actually seems impossible to implement. We cannot determine when a user is actually standing in the MicroPython prompt and typing SHIFT-UpArrow, or when the user is just playing around with their own program, which might also want to do something when it receives "UpArrow" signals, send to it.

Another possibility is that some user might want to make their own program that acts like a prompt:
```
def do_stuff(user_input):
    print("You typed: " + user_input)

while True:
    txt = input(">>> ")
    do_stuff(txt)
```

Which would even make the prompt-detection hard to do, because we can't differentiate. I'd like the REPL to be as similar to using PuTTy/picocom/etc. as possible, and trying to interfere in this way will probably introduce all kinds of problems. 

From a didactical standpoint, it is not a problem if a Python learner is forced to retype something, that will probably just help make it stick even better. Remember that Mu is designed for beginning programmers :)

I will close this issue, feel free to reopen it if you disagree.
