### ISSUE TITLE
Endless loops with print freezes Mu

### ISSUE THREAD

**Issue by gquintana** [mu-editor/mu#510]
When the code contains an endless loop, after a while the editor freezes

In this example, it freezes between 850000 - 860000 iterations (never the same value) 
```python
import random
i = 1
while True:
    x = random.randint(1, 6)
    if x >= 5:
        print("{} {}: Gagné".format(i, x))
    else:
        print("{} {}: Perdu".format(i, x))
    i = i + 1
```
It might be related to the log pane being full or some memory buffer being full.

Mu 1.0b16
Ubuntu Xenial

**Comment by carlosperate** [comment]
I can no longer replicate this in an Ubuntu VM, as it was probably fixed by https://github.com/mu-editor/mu/pull/723.
If this was about the REPL in micro:bit/CircuitPython/MicroPython mode, then issue should capture this as well #447.

I'll close this ticket as resolved, but please do reopen if you are still experiencing issues. Thanks for the report @gquintana!
