### ISSUE TITLE
Debugger: Debug inspector doesn't show anything when stepping through code

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#532]
When running the Python debugger the Debug Inspector works fine when a breakpoint is used, however when stepping through the script the Inspector doesn't update.

Gif below:

![mu_debug_inspector_2](https://user-images.githubusercontent.com/4189262/42422358-80cf2758-82dc-11e8-9aa9-35701cac4f44.gif)

**Comment by ntoll** [comment]
Good catch.

It turns out that `set_trace` was getting the frame from the currently running script (i.e. the debugger itself) and emitting the stack would emit the stack if it was the debugger's (which it would be). The `set_step` method stops at the next available line in the target script (to be debugged)... i.e. not the debugger, so the resulting stack will be emitted. ;-)

**Comment by carlosperate** [comment]
Thanks for the quick fix!

**Comment by ntoll** [comment]
Sure... an equally quick response on MicroPython blessed hex would be really appreciated. ;-)

**Comment by carlosperate** [comment]
> Sure... an equally quick response on MicroPython blessed hex would be really appreciated. ;-)

On it, going as fast as I can 🏎

**Comment by ntoll** [comment]
:hugs: :shipit:
