### ISSUE TITLE
help and docs

### ISSUE THREAD

**Issue by bazilione** [mu-editor/mu#596]
Please put together a web page (or as part of the Help) a list of available shortcuts. Please point me to it if I missed it. (Examples of why I'd like that: it is currently not obvious that "Save As" is double click on the tab (it is not the standard way of doing that); the same for Tab/Shift-Tab for indentation). A list of those would be nice.

**Comment by ntoll** [comment]
Everything you mentioned is covered in the tutorials linked from here:

https://codewith.mu/en/tutorials/

In particular, you should look at:

https://codewith.mu/en/tutorials/1.0/start (for the basics)
https://codewith.mu/en/tutorials/1.0/shortcuts (for shortcuts)

I'll close this since we already have documentation.
