### ISSUE TITLE
Mac OS X Application Wont Start

### ISSUE THREAD

**Issue by Coeptus** [mu-editor/mu#606]
I downloaded the newest version of Mu, installed it, gave permission to run third party software...and then the application fails to even launch.

When I try to start the application, the icon appears for ~1/2 second on the dock...and then disappears immediately. It doesn't seem to really open at all so there is something happening very quickly when it tries to start up.

I have a 13" Macbook Pro Retina (early 2015) and am running OS X Yosemite 10.10.5

Any help on this issue would be greatly appreciated. I am VERY new to coding, and trying to do things through a plain Text editor and then using "screen" command in terminal is turning out to be a little trickier than if I had color coded text editing with built in live view. It's almost like Mu was made for editing Adafruit CircuitPython code!!! ;)

Unfortunately I don't really have any code or error files because the App won't even start at all.

**Comment by ntoll** [comment]
Hi @Coeptus,

I'm afraid Mu only works on OSX 10.11 or more (I just checked, we mention it here: https://codewith.mu/en/howto/install_macos).

This is something we don't control since this constraint is forced on us by the tools and code libraries we use for building the OSX installer (i.e. *they* only support 10.11 or later).

The simplest solution would be to upgrade the OS to a newer version.

I'm so sorry I can't be of any more help. :-(

N.
