### ISSUE TITLE
Mu only supports Python 3.6 now?

### ISSUE THREAD

**Issue by bennuttall** [mu-editor/mu#669]
How come Mu now supports only Python 3.6 and above? Is there something in Mu which relies on 3.6? Raspbian Stretch has Python 3.5. If it's not a hard requirement we can build it anyway (and the version check should be removed), but if it really does require Python 3.6 we will be stuck on v1.0.0.

**Comment by ntoll** [comment]
Eyup @bennuttall,

It's to do with latest Qt (5.11) wheels only working against 3.6+ :-/ Riverbank are aware, and please reach out to the to fix the problem. (The error we see is that when using Python 3.5 Qt complains about an unknown symbol that was introduced in Python 3.6... i.e. they've broken their complication/build against Python 3.5).

Does this help?

AFAICT, you could remove the requirement and build things anyway since you're relying on Debian packaging of Qt here, right?

**Comment by bennuttall** [comment]
Ah ok, that makes sense. Should be fine for Pi. :+1:

**Comment by LuRsT** [comment]
Can this Issue be closed?

**Comment by carlosperate** [comment]
Does that mean the current Pi deb build process will include an additional step to apply a patch to remove those lines?

**Comment by carlosperate** [comment]
Related issues: https://github.com/mu-editor/mu/issues/575 and https://github.com/mu-editor/mu/issues/538

I've been looking into this and I think the issues is actually with versions of Python below 3.5.4. I couldn't replicate with Python 3.5.6 and 3.5.4, and then I noticed most of the report we had were on Python 3.5.2, and after testing that version I was finally able to replicate in macOS and Windows.

After a google search I've found this, so it looks the the symbol was introduced in 3.5.4:
https://riverbankcomputing.com/pipermail/pyqt/2018-July/040514.html

Thankfully Riverbank has released new wheels a couple of weeks ago, so I've tested them and we can remove the setup.py safeguard: PR https://github.com/mu-editor/mu/pull/678

**Comment by carlosperate** [comment]
The imposed restriction has been removed with PR #678, so I'll close this issue.

There is still more ongoing work to improve how Mu deals with dependencies in Raspbian, discussion can be found in issue https://github.com/mu-editor/mu/issues/671.

**Comment by bennuttall** [comment]
Mu now depends on Black, which requires Python 3.6 and above.

**Comment by ntoll** [comment]
@bennuttall why reopen this? Mu does **NOT** depend upon black. I was very careful and spent most of my Sunday making sure of this (the test suite both runs and passes with Python 3.5 on Travis). Like the plotter, this feature only appears when it can be supported. This effort can clearly be seen in the code attached to the relevant PR and in the comments created in the commits.

Please, please, please, please don't jump to conclusions.

If there is a Python 3.5 related problem the involves black, please raise a specific issue so I can fix it.

**Comment by bennuttall** [comment]
I just tried to run `setup.py` on a Raspberry Pi and it fails because `'black>=18.9b0` is in `install_requires` 

https://github.com/mu-editor/mu/blob/master/setup.py#L21

**Comment by bennuttall** [comment]
It seems the answer to the issue question is "no" but I got confused about how to install from source without Python 3.6.

It seems running `setup.py` will not honour the versioning in `requirements.txt`. Should black not be included in `setup.py` or should I not be installing it this way?

Sorry for the mix-up!

**Comment by ntoll** [comment]
OK, so this is a genuine bug. The simple solution is at add black to the `install_requires` list if Python is >= 3.6. I'd tested all other ways to get hold of Mu except (alas) via setup.py. Sorry about that.

**Comment by bennuttall** [comment]
It's worth noting that if the wheel is built with Python 3.6, it will include black in the requirements, and users will have a requirement on black. If it's built with 3.5, they won't, regardless of their own Python version. I think @carlosperate had a solution when I raised it in #671.

**Comment by carlosperate** [comment]
Environmental markers can be used inside setup.py to only install black with Python > 3.5. As Ben mentioned, this is needed for correct wheels for the next alpha release. Otherwise users running `pip install mu-editor` with Python 3.5 will end up with installation errors.

Independently of the other issues with Wheels and ARM-based platforms, I think this is a required change.

--- 
As part of issue #671 PR #680 was created to use environmental markers to exclude dependencies for ARM-based platforms (a nice side effect was to remove the need to keep an additional requirements_pi.txt, as the new requirements.txt file would work in all platforms). This fixes the issue of PyPi wheels giving out errors in Raspberry Pi when the user runs `pip install mu-editor`, but 

I could rebase it and get it ready for the next alpha, but I think if we do that, we should also add a second PR to inform users about the missing dependencies in ARM (as mentioned in https://github.com/mu-editor/mu/issues/671#issuecomment-430671069 and https://github.com/mu-editor/mu/issues/671#issuecomment-431449139), or find a different work around:

>Next step would be to add a bit of code at import time to detect missing PyQt5 dependencies when running on ARM and point the user to https://mu.readthedocs.io/en/latest/setup.html#raspberry-pi and possibly https://codewith.mu/en/howto/install_raspberry_pi (although if a user has purposely tried to install via PyPi in their Pi, then perhaps the first link is more useful? Not sure).
Unless we can think of a better solution?

**Comment by ntoll** [comment]
@carlosperate aha... thanks for pointing out how these two things cross over and complement each other.

I'll check/merge and update right now.

**Comment by ntoll** [comment]
OK... so a fix I added to #680 should fix the `setup.py` related problems.

Thanks for your patience and help with all this. Sorry for the cock up on my part.

**Comment by bennuttall** [comment]
Thank you both :1st_place_medal:

**Comment by bennuttall** [comment]
Can confirm the issue has gone away :+1:

**Comment by ntoll** [comment]
@bennuttall stonking.
