### ISSUE TITLE
Version 1.0.1 installation on Raspberry Pi Stretch does not work (easily)

### ISSUE THREAD

**Issue by topshed** [mu-editor/mu#688]
(installing from apt only provides version 1.0.0)
1) Installing via pip3 fails:

>   Could not find a version that satisfies the requirement pyqt5==5.11.2 (from mu-editor) (from versions: )
No matching distribution found for pyqt5==5.11.2 (from mu-editor)

2) So install the packages that provides this via apt (sudo apt install python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtserialport python3-pyqt5.qtsvg) and trying again via pip3 gets further but still eventually fails with the same error. 

3) Try cloning this repo and installing via setup.py but this fails with:

> File "/tmp/easy_install-dmln7k2q/Pillow-5.3.0/setup.py", line 814, in <module>
setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for jpeg,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n',)

4) Running sudo pip3 install pillow --upgrade then retying setup.py from the repo seems to work (no errors) but when running mu-editor, it bombs out with 

> ImportError: No module named 'qtconsole'

5) So install python3-qtconsole via apt and mu-editor 1.0.1 finally will run.

**But the plotter capability is not available!** (issue #689)

**Comment by ntoll** [comment]
@topshed sorry to hear you've been having problems. The instructions of setting up Mu on a Pi (as in not apt) are in the developer docs here: https://mu.readthedocs.io/en/latest/setup.html#raspberry-pi If you think we've missed a step, please feel free to send over a PR with any updates.

As for the plotter, it's not available in Mu on RPi because the right sort of dependencies are not in Raspbian (yet). This is something over which we don't have any control.

I'll close this issue since the stuff it deals with is pretty much beyond the control of Mu-maintainers to fix.
