### ISSUE TITLE
Autocompletion in method

### ISSUE THREAD

**Issue by JLFra** [mu-editor/mu#968]
Could you add autocompletion in the argument of methods please. Autocompletion works, but not in methods?
Thanks
Julien

**Comment by ZanderBrown** [comment]
Could you clarify " in the argument of methods "?

Do you mean between the ( and ) of a function/method call? In which case I assume you're looking for suggestions of local variables which would require the autocompletion to be far cleverer than it is at the moment

**Comment by JLFra** [comment]
Yes, exactly. Autocompletion works perfectly outside method, but not inside.

**Comment by carlosperate** [comment]
Is this because the autocompletion is showing the function docs?

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4189262/98591048-9ba43b80-22c7-11eb-9358-07ac49e9ded8.png">

In this case, pressing escape closes the current info and suggest a variable:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/4189262/98591168-c42c3580-22c7-11eb-8494-6bb2a8a8512d.png">

**Comment by carlosperate** [comment]
This behaviour is defined by QScintilla, so not much we can do within Mu itself, so we can consider the current behaviour acceptable.
